# Generated by Django 4.0.6 on 2022-07-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=200)),
                ('lider', models.CharField(max_length=200)),
                ('numero_de_participantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regiao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lider', models.CharField(max_length=200)),
                ('foto', models.URLField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regiao')),
            ],
        ),
    ]
