# Generated by Django 4.0.6 on 2022-07-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_groups_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lider'),
        ),
    ]
