# Generated by Django 4.0.6 on 2022-07-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_grupo_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='link',
            field=models.URLField(default='https://web.whatsapp.com/'),
            preserve_default=False,
        ),
    ]
